modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/ReezaVT/Pixelmon-Spawn-Alerts/issues"
[[mods]]
modId = "spawn-alerts"
version = "${file.jarVersion}"
displayName = "Pixelmon Spawn Alerts"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/pixelmon-spawn-alerts/"
logoFile = "logo.png"
credits = "Nintendo for the idea and the sound effect."
authors = "ReezaVT"
description = '''
A Pixelmon Reforged addon which adds customizable spawn alerts for Pokemon.
'''

[[dependencies.spawn-alerts]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spawn-alerts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5]"
ordering = "NONE"
side = "BOTH"

[[dependencies.spawn-alerts]]
modId = "pixelmon"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"